

// ------------------------------------------------------------------------------------------------
// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.com/).
// Created by Simon Hughes (https://about.me/simon.hughes).
// 
// Do not make changes directly to this file - edit the template instead.
// 
// The following connection settings were used to generate this file:
//     Configuration file:     "EntityFramework.Reverse.POCO.Generator\App.config"
//     Connection String Name: "MyDbContextSqlCE4"
//     Connection String:      "Data Source=F:\_workspace\lab\EntityFramework-Reverse-POCO-Code-First-Generator\Tester.BusinessLogic\App_Data\NorthwindSqlCe40.sdf"
// ------------------------------------------------------------------------------------------------

// -----------------------------------------------------------------------------------------
// Failed to read database schema in LoadTables() - 路径无效。请检查数据库的目录。 [ Path = F:\_workspace\lab\EntityFramework-Reverse-POCO-Code-First-Generator\Tester.BusinessLogic\App_Data\NorthwindSqlCe40.sdf ]
// -----------------------------------------------------------------------------------------

