

// ------------------------------------------------------------------------------------------------
// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.com/).
// Created by Simon Hughes (https://about.me/simon.hughes).
// 
// Do not make changes directly to this file - edit the template instead.
// 
// The following connection settings were used to generate this file:
//     Configuration file:     "EntityFramework.Reverse.POCO.Generator\App.config"
//     Connection String Name: "MyDbContextSqlCE4"
//     Connection String:      "Data Source=J:\lab\EntityFramework-Reverse-POCO-Code-First-Generator\EntityFramework.Reverse.POCO.Generator\App_Data\NorthwindSqlCe40.sdf"
// ------------------------------------------------------------------------------------------------
// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using Microsoft.Data.Entity;
using Microsoft.Data.Entity.Metadata.Builders;
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq.Expressions;

namespace EntityFramework_Reverse_POCO_Generator.SqlCe4
{
    using System.Linq;

    // ************************************************************************
    // Unit of work
    public interface IMyDbContextSqlCE4 : System.IDisposable
    {
        Microsoft.Data.Entity.DbSet<Category> Categories { get; set; } // Categories
        Microsoft.Data.Entity.DbSet<Customer> Customers { get; set; } // Customers
        Microsoft.Data.Entity.DbSet<Employee> Employees { get; set; } // Employees
        Microsoft.Data.Entity.DbSet<Order> Orders { get; set; } // Orders
        Microsoft.Data.Entity.DbSet<OrderDetail> OrderDetails { get; set; } // Order Details
        Microsoft.Data.Entity.DbSet<Product> Products { get; set; } // Products
        Microsoft.Data.Entity.DbSet<Shipper> Shippers { get; set; } // Shippers
        Microsoft.Data.Entity.DbSet<Supplier> Suppliers { get; set; } // Suppliers

        int SaveChanges();
        int SaveChanges(bool acceptAllChangesOnSuccess);
        System.Threading.Tasks.Task<int> SaveChangesAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        System.Threading.Tasks.Task<int> SaveChangesAsync(bool acceptAllChangesOnSuccess, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
    }

    // ************************************************************************
    // Database context
    public class MyDbContextSqlCE4 : Microsoft.Data.Entity.DbContext, IMyDbContextSqlCE4
    {
        public Microsoft.Data.Entity.DbSet<Category> Categories { get; set; } // Categories
        public Microsoft.Data.Entity.DbSet<Customer> Customers { get; set; } // Customers
        public Microsoft.Data.Entity.DbSet<Employee> Employees { get; set; } // Employees
        public Microsoft.Data.Entity.DbSet<Order> Orders { get; set; } // Orders
        public Microsoft.Data.Entity.DbSet<OrderDetail> OrderDetails { get; set; } // Order Details
        public Microsoft.Data.Entity.DbSet<Product> Products { get; set; } // Products
        public Microsoft.Data.Entity.DbSet<Shipper> Shippers { get; set; } // Shippers
        public Microsoft.Data.Entity.DbSet<Supplier> Suppliers { get; set; } // Suppliers

#if false
        static MyDbContextSqlCE4()
        {
            Microsoft.Data.Entity.Database.SetInitializer<MyDbContextSqlCE4>(null);
        }
#endif

        public MyDbContextSqlCE4()
        {
        }

#if false
        public MyDbContextSqlCE4(string connectionString) : base(connectionString)
        {
        }

        public MyDbContextSqlCE4(string connectionString, Microsoft.Data.Entity.Infrastructure.DbCompiledModel model) : base(connectionString, model)
        {
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }
#endif

        protected override void OnModelCreating(Microsoft.Data.Entity.ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            modelBuilder.Add(new CategoryConfiguration());
            modelBuilder.Add(new CustomerConfiguration());
            modelBuilder.Add(new EmployeeConfiguration());
            modelBuilder.Add(new OrderConfiguration());
            modelBuilder.Add(new OrderDetailConfiguration());
            modelBuilder.Add(new ProductConfiguration());
            modelBuilder.Add(new ShipperConfiguration());
            modelBuilder.Add(new SupplierConfiguration());
        }

        public static Microsoft.Data.Entity.ModelBuilder CreateModel(Microsoft.Data.Entity.ModelBuilder modelBuilder, string schema)
        {
            modelBuilder.Add(new CategoryConfiguration(), schema);
            modelBuilder.Add(new CustomerConfiguration(), schema);
            modelBuilder.Add(new EmployeeConfiguration(), schema);
            modelBuilder.Add(new OrderConfiguration(), schema);
            modelBuilder.Add(new OrderDetailConfiguration(), schema);
            modelBuilder.Add(new ProductConfiguration(), schema);
            modelBuilder.Add(new ShipperConfiguration(), schema);
            modelBuilder.Add(new SupplierConfiguration(), schema);
            return modelBuilder;
        }
    }
#warning AddUnitTestingDbContext is not really work with EF7

    // ************************************************************************
    // Fake Database context
    [System.CodeDom.Compiler.GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.18.1.0")]
    public class FakeMyDbContextSqlCE4 : IMyDbContextSqlCE4
    {
        public Microsoft.Data.Entity.DbSet<Category> Categories { get; set; }
        public Microsoft.Data.Entity.DbSet<Customer> Customers { get; set; }
        public Microsoft.Data.Entity.DbSet<Employee> Employees { get; set; }
        public Microsoft.Data.Entity.DbSet<Order> Orders { get; set; }
        public Microsoft.Data.Entity.DbSet<OrderDetail> OrderDetails { get; set; }
        public Microsoft.Data.Entity.DbSet<Product> Products { get; set; }
        public Microsoft.Data.Entity.DbSet<Shipper> Shippers { get; set; }
        public Microsoft.Data.Entity.DbSet<Supplier> Suppliers { get; set; }

        public FakeMyDbContextSqlCE4()
        {
            Categories = new FakeDbSet<Category>("CategoryId");
            Customers = new FakeDbSet<Customer>("CustomerId");
            Employees = new FakeDbSet<Employee>("EmployeeId");
            Orders = new FakeDbSet<Order>("OrderId");
            OrderDetails = new FakeDbSet<OrderDetail>("OrderId", "ProductId");
            Products = new FakeDbSet<Product>("ProductId");
            Shippers = new FakeDbSet<Shipper>("ShipperId");
            Suppliers = new FakeDbSet<Supplier>("SupplierId");
        }
        
        public int SaveChangesCount { get; private set; } 
        public int SaveChanges()
        {
            return SaveChanges(true);
        }
        public int SaveChanges(bool acceptAllChangesOnSuccess)
        {
            ++SaveChangesCount;
            return 1;
        }

        public System.Threading.Tasks.Task<int> SaveChangesAsync(bool acceptAllChangesOnSuccess, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            ++SaveChangesCount;
            return System.Threading.Tasks.Task<int>.Factory.StartNew(() => 1, cancellationToken);
        }

        public System.Threading.Tasks.Task<int> SaveChangesAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            return SaveChangesAsync(true, cancellationToken);
        }

        protected virtual void Dispose(bool disposing)
        {
        }
        
        public void Dispose()
        {
            Dispose(true);
        }
    }
#warning AddUnitTestingDbContext is not really work with EF7

    // ************************************************************************
    // Fake DbSet
    // Implementing Find:
    //      The Find method is difficult to implement in a generic fashion. If
    //      you need to test code that makes use of the Find method it is
    //      easiest to create a test DbSet for each of the entity types that
    //      need to support find. You can then write logic to find that
    //      particular type of entity, as shown below:
    //      public class FakeBlogDbSet : FakeDbSet<Blog>
    //      {
    //          public override Blog Find(params object[] keyValues)
    //          {
    //              var id = (int) keyValues.Single();
    //              return this.SingleOrDefault(b => b.BlogId == id);
    //          }
    //      }
    //      Read more about it here: https://msdn.microsoft.com/en-us/data/dn314431.aspx
    [System.CodeDom.Compiler.GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.18.1.0")]
    public class FakeDbSet<TEntity> : Microsoft.Data.Entity.DbSet<TEntity>, IQueryable, System.Collections.Generic.IEnumerable<TEntity>, Microsoft.Data.Entity.Query.Internal.IAsyncEnumerableAccessor<TEntity>, Microsoft.Data.Entity.Infrastructure.IInfrastructure<IServiceProvider> where TEntity : class 
    { 
#warning This won't works.
        private readonly System.Reflection.PropertyInfo[] _primaryKeys;
        private readonly System.Collections.ObjectModel.ObservableCollection<TEntity> _data;
        private readonly IQueryable _query;
 
        public FakeDbSet() 
        { 
            _data = new System.Collections.ObjectModel.ObservableCollection<TEntity>(); 
            _query = _data.AsQueryable(); 
        }

        public FakeDbSet(params string[] primaryKeys)
        {
            _primaryKeys = typeof(TEntity).GetProperties().Where(x => primaryKeys.Contains(x.Name)).ToArray();
            _data = new System.Collections.ObjectModel.ObservableCollection<TEntity>(); 
            _query = _data.AsQueryable(); 
        }

        System.Collections.Generic.IAsyncEnumerable<TEntity> Microsoft.Data.Entity.Query.Internal.IAsyncEnumerableAccessor<TEntity>.AsyncEnumerable
        {
            get
            {
                return new FakeDbAsyncEnumerable<TEntity>(_data);
            }
        }

        System.Type IQueryable.ElementType
        {
            get { return _query.ElementType; }
        }

        System.Linq.Expressions.Expression IQueryable.Expression
        {
            get { return _query.Expression; }
        }

        IQueryProvider IQueryable.Provider 
        { 
            get { return new FakeDbAsyncQueryProvider<TEntity>(_query.Provider); } 
        } 

        IServiceProvider Microsoft.Data.Entity.Infrastructure.IInfrastructure<IServiceProvider>.Instance
        {
            get
            {
                throw new NotImplementedException();
            }
        }

        public override Microsoft.Data.Entity.ChangeTracking.EntityEntry<TEntity> Add(TEntity entity, GraphBehavior behavior = GraphBehavior.IncludeDependents)
        {
            if (entity == null) throw new System.ArgumentNullException("entity");
            _data.Add(entity);
            return base.Add(entity, behavior);
        }

        public override void AddRange(params TEntity[] entities)
        {
            if (entities == null) throw new System.ArgumentNullException("entities");
            foreach (var entity in entities)
            {
                _data.Add(entity);
            }
        }

        public override void AddRange(System.Collections.Generic.IEnumerable<TEntity> entities, GraphBehavior behavior = GraphBehavior.IncludeDependents)
        {
            if (entities == null) throw new System.ArgumentNullException("entities");
            var items = entities.ToList();
            foreach (var entity in items)
            {
                _data.Add(entity);
            }
        }

        public override Microsoft.Data.Entity.ChangeTracking.EntityEntry<TEntity> Attach(TEntity entity, GraphBehavior behavior = GraphBehavior.IncludeDependents)
        {
            return base.Attach(entity, behavior);
        }

        public override void AttachRange(System.Collections.Generic.IEnumerable<TEntity> entities, GraphBehavior behavior = GraphBehavior.IncludeDependents)
        {
            base.AttachRange(entities, behavior);
        }

        public override void AttachRange(params TEntity[] entities)
        {
            base.AttachRange(entities);
        }

        public override Microsoft.Data.Entity.ChangeTracking.EntityEntry<TEntity> Remove(TEntity entity)
        {
            if (entity == null) throw new System.ArgumentNullException("entity");
            _data.Remove(entity);
            return base.Remove(entity);
        }

        public override void RemoveRange(System.Collections.Generic.IEnumerable<TEntity> entities)
        {
            if (entities == null) throw new System.ArgumentNullException("entities");
            var items = entities.ToList();
            foreach (var entity in items)
            {
                _data.Remove(entity);
            }
        }

        public override void RemoveRange(params TEntity[] entities)
        {
            if (entities == null) throw new System.ArgumentNullException("entities");
            foreach (var entity in entities)
            {
                _data.Remove(entity);
            }
        }

        public override Microsoft.Data.Entity.ChangeTracking.EntityEntry<TEntity> Update(TEntity entity, GraphBehavior behavior = GraphBehavior.IncludeDependents)
        {
            return base.Update(entity, behavior);
        }
        public override void UpdateRange(System.Collections.Generic.IEnumerable<TEntity> entities, GraphBehavior behavior = GraphBehavior.IncludeDependents)
        {
            base.UpdateRange(entities, behavior);
        }

        public override void UpdateRange(params TEntity[] entities)
        {
            base.UpdateRange(entities);
        }

        System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator()
        {
            return _data.GetEnumerator();
        }

        System.Collections.Generic.IEnumerator<TEntity> System.Collections.Generic.IEnumerable<TEntity>.GetEnumerator()
        {
            return _data.GetEnumerator();
        }
    } 
 
    public class FakeDbAsyncQueryProvider<TEntity> : Microsoft.Data.Entity.Query.Internal.IAsyncQueryProvider 
    { 
        private readonly IQueryProvider _inner; 
 
        public FakeDbAsyncQueryProvider(IQueryProvider inner) 
        { 
            _inner = inner; 
        } 
 
        public IQueryable CreateQuery(System.Linq.Expressions.Expression expression) 
        { 
            return new FakeDbAsyncEnumerable<TEntity>(expression); 
        } 
 
        public IQueryable<TElement> CreateQuery<TElement>(System.Linq.Expressions.Expression expression) 
        { 
            return new FakeDbAsyncEnumerable<TElement>(expression); 
        } 
 
        public object Execute(System.Linq.Expressions.Expression expression) 
        { 
            return _inner.Execute(expression); 
        } 
 
        public TResult Execute<TResult>(System.Linq.Expressions.Expression expression) 
        { 
            return _inner.Execute<TResult>(expression); 
        } 
 
        public System.Threading.Tasks.Task<TResult> ExecuteAsync<TResult>(System.Linq.Expressions.Expression expression, System.Threading.CancellationToken cancellationToken) 
        { 
            return System.Threading.Tasks.Task.FromResult(Execute<TResult>(expression)); 
        }
 
        public System.Collections.Generic.IAsyncEnumerable<TResult> ExecuteAsync<TResult>(System.Linq.Expressions.Expression expression)
        {
            return new FakeDbAsyncEnumerable<TResult>(CreateQuery<TResult>(expression));
        }
    } 
 
    public class FakeDbAsyncEnumerable<T> : EnumerableQuery<T>, System.Collections.Generic.IAsyncEnumerable<T>, IQueryable<T> 
    { 
        public FakeDbAsyncEnumerable(System.Collections.Generic.IEnumerable<T> enumerable) 
            : base(enumerable) 
        { } 
 
        public FakeDbAsyncEnumerable(System.Linq.Expressions.Expression expression) 
            : base(expression) 
        { } 
 
        public System.Collections.Generic.IAsyncEnumerator<T> GetEnumerator() 
        { 
            return new FakeDbAsyncEnumerator<T>(this.AsEnumerable().GetEnumerator()); 
        } 
 
        IQueryProvider IQueryable.Provider 
        { 
            get { return new FakeDbAsyncQueryProvider<T>(this); } 
        } 
    } 
 
    public class FakeDbAsyncEnumerator<T> : System.Collections.Generic.IAsyncEnumerator<T> 
    { 
        private readonly System.Collections.Generic.IEnumerator<T> _inner; 
 
        public FakeDbAsyncEnumerator(System.Collections.Generic.IEnumerator<T> inner) 
        { 
            _inner = inner; 
        } 
 
        public void Dispose() 
        { 
            _inner.Dispose(); 
        } 
 
        public System.Threading.Tasks.Task<bool> MoveNext(System.Threading.CancellationToken cancellationToken) 
        { 
            return System.Threading.Tasks.Task.FromResult(_inner.MoveNext()); 
        } 
 
        public T Current 
        { 
            get { return _inner.Current; } 
        } 
    }

    // ************************************************************************
    // POCO classes

    // Categories
    [System.CodeDom.Compiler.GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.18.1.0")]
    public class Category
    {
        public int CategoryId { get; set; } // Category ID (Primary key)
        public string CategoryName { get; set; } // Category Name (length: 15)
        public string Description { get; set; } // Description (length: 536870911)
        public byte[] Picture { get; set; } // Picture (length: 1073741823)

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<Product> Products { get; set; } // Products.Products_FK01
        
        public Category()
        {
            Products = new System.Collections.Generic.List<Product>();
        }
    }

    // Customers
    [System.CodeDom.Compiler.GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.18.1.0")]
    public class Customer
    {
        public string CustomerId { get; set; } // Customer ID (Primary key) (length: 5)
        public string CompanyName { get; set; } // Company Name (length: 40)
        public string ContactName { get; set; } // Contact Name (length: 30)
        public string ContactTitle { get; set; } // Contact Title (length: 30)
        public string Address { get; set; } // Address (length: 60)
        public string City { get; set; } // City (length: 15)
        public string Region { get; set; } // Region (length: 15)
        public string PostalCode { get; set; } // Postal Code (length: 10)
        public string Country { get; set; } // Country (length: 15)
        public string Phone { get; set; } // Phone (length: 24)
        public string Fax { get; set; } // Fax (length: 24)

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<Order> Orders { get; set; } // Orders.Orders_FK00
        
        public Customer()
        {
            Orders = new System.Collections.Generic.List<Order>();
        }
    }

    // Employees
    [System.CodeDom.Compiler.GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.18.1.0")]
    public class Employee
    {
        public int EmployeeId { get; set; } // Employee ID (Primary key)
        public string LastName { get; set; } // Last Name (length: 20)
        public string FirstName { get; set; } // First Name (length: 10)
        public string Title { get; set; } // Title (length: 30)
        public System.DateTime? BirthDate { get; set; } // Birth Date
        public System.DateTime? HireDate { get; set; } // Hire Date
        public string Address { get; set; } // Address (length: 60)
        public string City { get; set; } // City (length: 15)
        public string Region { get; set; } // Region (length: 15)
        public string PostalCode { get; set; } // Postal Code (length: 10)
        public string Country { get; set; } // Country (length: 15)
        public string HomePhone { get; set; } // Home Phone (length: 24)
        public string Extension { get; set; } // Extension (length: 4)
        public byte[] Photo { get; set; } // Photo (length: 1073741823)
        public string Notes { get; set; } // Notes (length: 536870911)
        public int? ReportsTo { get; set; } // Reports To

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<Order> Orders { get; set; } // Orders.Orders_FK02
        
        public Employee()
        {
            Orders = new System.Collections.Generic.List<Order>();
        }
    }

    // Orders
    [System.CodeDom.Compiler.GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.18.1.0")]
    public class Order
    {
        public int OrderId { get; set; } // Order ID (Primary key)
        public string CustomerId { get; set; } // Customer ID (length: 5)
        public int? EmployeeId { get; set; } // Employee ID
        public string ShipName { get; set; } // Ship Name (length: 40)
        public string ShipAddress { get; set; } // Ship Address (length: 60)
        public string ShipCity { get; set; } // Ship City (length: 15)
        public string ShipRegion { get; set; } // Ship Region (length: 15)
        public string ShipPostalCode { get; set; } // Ship Postal Code (length: 10)
        public string ShipCountry { get; set; } // Ship Country (length: 15)
        public int? ShipVia { get; set; } // Ship Via
        public System.DateTime? OrderDate { get; set; } // Order Date
        public System.DateTime? RequiredDate { get; set; } // Required Date
        public System.DateTime? ShippedDate { get; set; } // Shipped Date
        public decimal? Freight { get; set; } // Freight

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<OrderDetail> OrderDetails { get; set; } // Many to many mapping

        // Foreign keys
        public virtual Customer Customer { get; set; } // Orders_FK00
        public virtual Employee Employee { get; set; } // Orders_FK02
        public virtual Shipper Shipper { get; set; } // Orders_FK01
        
        public Order()
        {
            OrderDetails = new System.Collections.Generic.List<OrderDetail>();
        }
    }

    // Order Details
    public class OrderDetail
    {
        public int OrderId { get; set; } // Order ID (Primary key)
        public int ProductId { get; set; } // Product ID (Primary key)
        public decimal UnitPrice { get; set; } // Unit Price
        public short Quantity { get; set; } // Quantity
        public float Discount { get; set; } // Discount

        // Foreign keys
        public virtual Order Order { get; set; } // Order Details_FK01
        public virtual Product Product { get; set; } // Order Details_FK00
    }

    // Products
    [System.CodeDom.Compiler.GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.18.1.0")]
    public class Product
    {
        public int ProductId { get; set; } // Product ID (Primary key)
        public int? SupplierId { get; set; } // Supplier ID
        public int? CategoryId { get; set; } // Category ID
        public string ProductName { get; set; } // Product Name (length: 40)
        public string EnglishName { get; set; } // English Name (length: 40)
        public string QuantityPerUnit { get; set; } // Quantity Per Unit (length: 20)
        public decimal? UnitPrice { get; set; } // Unit Price
        public short? UnitsInStock { get; set; } // Units In Stock
        public short? UnitsOnOrder { get; set; } // Units On Order
        public short? ReorderLevel { get; set; } // Reorder Level
        public bool Discontinued { get; set; } // Discontinued

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<OrderDetail> OrderDetails { get; set; } // Many to many mapping

        // Foreign keys
        public virtual Category Category { get; set; } // Products_FK01
        public virtual Supplier Supplier { get; set; } // Products_FK00
        
        public Product()
        {
            OrderDetails = new System.Collections.Generic.List<OrderDetail>();
        }
    }

    // Shippers
    [System.CodeDom.Compiler.GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.18.1.0")]
    public class Shipper
    {
        public int ShipperId { get; set; } // Shipper ID (Primary key)
        public string CompanyName { get; set; } // Company Name (length: 40)

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<Order> Orders { get; set; } // Orders.Orders_FK01
        
        public Shipper()
        {
            Orders = new System.Collections.Generic.List<Order>();
        }
    }

    // Suppliers
    [System.CodeDom.Compiler.GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.18.1.0")]
    public class Supplier
    {
        public int SupplierId { get; set; } // Supplier ID (Primary key)
        public string CompanyName { get; set; } // Company Name (length: 40)
        public string ContactName { get; set; } // Contact Name (length: 30)
        public string ContactTitle { get; set; } // Contact Title (length: 30)
        public string Address { get; set; } // Address (length: 60)
        public string City { get; set; } // City (length: 15)
        public string Region { get; set; } // Region (length: 15)
        public string PostalCode { get; set; } // Postal Code (length: 10)
        public string Country { get; set; } // Country (length: 15)
        public string Phone { get; set; } // Phone (length: 24)
        public string Fax { get; set; } // Fax (length: 24)

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<Product> Products { get; set; } // Products.Products_FK00
        
        public Supplier()
        {
            Products = new System.Collections.Generic.List<Product>();
        }
    }


    // ************************************************************************
    // POCO Configuration

    // Categories
    public class CategoryConfiguration : EntityTypeConfiguration<Category>
    {
 
        public void Config(Microsoft.Data.Entity.Metadata.Builders.EntityTypeBuilder<Category> builder, string schema)
        {
            builder.ToTable("Categories", schema);
            builder.HasKey(x => x.CategoryId);

            builder.Property(x => x.CategoryId).HasColumnName("Category ID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            builder.Property(x => x.CategoryName).HasColumnName("Category Name").IsRequired().HasColumnType("nvarchar").HasMaxLength(15);
            builder.Property(x => x.Description).HasColumnName("Description").IsOptional().HasColumnType("ntext").IsMaxLength();
            builder.Property(x => x.Picture).HasColumnName("Picture").IsOptional().HasColumnType("image").HasMaxLength(1073741823);
        }
    }

    // Customers
    public class CustomerConfiguration : EntityTypeConfiguration<Customer>
    {
 
        public void Config(Microsoft.Data.Entity.Metadata.Builders.EntityTypeBuilder<Customer> builder, string schema)
        {
            builder.ToTable("Customers", schema);
            builder.HasKey(x => x.CustomerId);

            builder.Property(x => x.CustomerId).HasColumnName("Customer ID").IsRequired().HasColumnType("nvarchar").HasMaxLength(5).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            builder.Property(x => x.CompanyName).HasColumnName("Company Name").IsRequired().HasColumnType("nvarchar").HasMaxLength(40);
            builder.Property(x => x.ContactName).HasColumnName("Contact Name").IsOptional().HasColumnType("nvarchar").HasMaxLength(30);
            builder.Property(x => x.ContactTitle).HasColumnName("Contact Title").IsOptional().HasColumnType("nvarchar").HasMaxLength(30);
            builder.Property(x => x.Address).HasColumnName("Address").IsOptional().HasColumnType("nvarchar").HasMaxLength(60);
            builder.Property(x => x.City).HasColumnName("City").IsOptional().HasColumnType("nvarchar").HasMaxLength(15);
            builder.Property(x => x.Region).HasColumnName("Region").IsOptional().HasColumnType("nvarchar").HasMaxLength(15);
            builder.Property(x => x.PostalCode).HasColumnName("Postal Code").IsOptional().HasColumnType("nvarchar").HasMaxLength(10);
            builder.Property(x => x.Country).HasColumnName("Country").IsOptional().HasColumnType("nvarchar").HasMaxLength(15);
            builder.Property(x => x.Phone).HasColumnName("Phone").IsOptional().HasColumnType("nvarchar").HasMaxLength(24);
            builder.Property(x => x.Fax).HasColumnName("Fax").IsOptional().HasColumnType("nvarchar").HasMaxLength(24);
        }
    }

    // Employees
    public class EmployeeConfiguration : EntityTypeConfiguration<Employee>
    {
 
        public void Config(Microsoft.Data.Entity.Metadata.Builders.EntityTypeBuilder<Employee> builder, string schema)
        {
            builder.ToTable("Employees", schema);
            builder.HasKey(x => x.EmployeeId);

            builder.Property(x => x.EmployeeId).HasColumnName("Employee ID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            builder.Property(x => x.LastName).HasColumnName("Last Name").IsRequired().HasColumnType("nvarchar").HasMaxLength(20);
            builder.Property(x => x.FirstName).HasColumnName("First Name").IsRequired().HasColumnType("nvarchar").HasMaxLength(10);
            builder.Property(x => x.Title).HasColumnName("Title").IsOptional().HasColumnType("nvarchar").HasMaxLength(30);
            builder.Property(x => x.BirthDate).HasColumnName("Birth Date").IsOptional().HasColumnType("datetime");
            builder.Property(x => x.HireDate).HasColumnName("Hire Date").IsOptional().HasColumnType("datetime");
            builder.Property(x => x.Address).HasColumnName("Address").IsOptional().HasColumnType("nvarchar").HasMaxLength(60);
            builder.Property(x => x.City).HasColumnName("City").IsOptional().HasColumnType("nvarchar").HasMaxLength(15);
            builder.Property(x => x.Region).HasColumnName("Region").IsOptional().HasColumnType("nvarchar").HasMaxLength(15);
            builder.Property(x => x.PostalCode).HasColumnName("Postal Code").IsOptional().HasColumnType("nvarchar").HasMaxLength(10);
            builder.Property(x => x.Country).HasColumnName("Country").IsOptional().HasColumnType("nvarchar").HasMaxLength(15);
            builder.Property(x => x.HomePhone).HasColumnName("Home Phone").IsOptional().HasColumnType("nvarchar").HasMaxLength(24);
            builder.Property(x => x.Extension).HasColumnName("Extension").IsOptional().HasColumnType("nvarchar").HasMaxLength(4);
            builder.Property(x => x.Photo).HasColumnName("Photo").IsOptional().HasColumnType("image").HasMaxLength(1073741823);
            builder.Property(x => x.Notes).HasColumnName("Notes").IsOptional().HasColumnType("ntext").IsMaxLength();
            builder.Property(x => x.ReportsTo).HasColumnName("Reports To").IsOptional().HasColumnType("int");
        }
    }

    // Orders
    public class OrderConfiguration : EntityTypeConfiguration<Order>
    {
 
        public void Config(Microsoft.Data.Entity.Metadata.Builders.EntityTypeBuilder<Order> builder, string schema)
        {
            builder.ToTable("Orders", schema);
            builder.HasKey(x => x.OrderId);

            builder.Property(x => x.OrderId).HasColumnName("Order ID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            builder.Property(x => x.CustomerId).HasColumnName("Customer ID").IsRequired().HasColumnType("nvarchar").HasMaxLength(5);
            builder.Property(x => x.EmployeeId).HasColumnName("Employee ID").IsOptional().HasColumnType("int");
            builder.Property(x => x.ShipName).HasColumnName("Ship Name").IsOptional().HasColumnType("nvarchar").HasMaxLength(40);
            builder.Property(x => x.ShipAddress).HasColumnName("Ship Address").IsOptional().HasColumnType("nvarchar").HasMaxLength(60);
            builder.Property(x => x.ShipCity).HasColumnName("Ship City").IsOptional().HasColumnType("nvarchar").HasMaxLength(15);
            builder.Property(x => x.ShipRegion).HasColumnName("Ship Region").IsOptional().HasColumnType("nvarchar").HasMaxLength(15);
            builder.Property(x => x.ShipPostalCode).HasColumnName("Ship Postal Code").IsOptional().HasColumnType("nvarchar").HasMaxLength(10);
            builder.Property(x => x.ShipCountry).HasColumnName("Ship Country").IsOptional().HasColumnType("nvarchar").HasMaxLength(15);
            builder.Property(x => x.ShipVia).HasColumnName("Ship Via").IsOptional().HasColumnType("int");
            builder.Property(x => x.OrderDate).HasColumnName("Order Date").IsOptional().HasColumnType("datetime");
            builder.Property(x => x.RequiredDate).HasColumnName("Required Date").IsOptional().HasColumnType("datetime");
            builder.Property(x => x.ShippedDate).HasColumnName("Shipped Date").IsOptional().HasColumnType("datetime");
            builder.Property(x => x.Freight).HasColumnName("Freight").IsOptional().HasColumnType("money").HasPrecision(19,4);

            // Foreign keys
            builder.HasOptional(a => a.Employee).WithMany(b => b.Orders).HasForeignKey(c => c.EmployeeId); // Orders_FK02
            builder.HasOptional(a => a.Shipper).WithMany(b => b.Orders).HasForeignKey(c => c.ShipVia); // Orders_FK01
            builder.HasRequired(a => a.Customer).WithMany(b => b.Orders).HasForeignKey(c => c.CustomerId); // Orders_FK00
        }
    }

    // Order Details
    public class OrderDetailConfiguration : EntityTypeConfiguration<OrderDetail>
    {
 
        public void Config(Microsoft.Data.Entity.Metadata.Builders.EntityTypeBuilder<OrderDetail> builder, string schema)
        {
            builder.ToTable("Order Details", schema);
            builder.HasKey(x => new { x.OrderId, x.ProductId });

            builder.Property(x => x.OrderId).HasColumnName("Order ID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            builder.Property(x => x.ProductId).HasColumnName("Product ID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            builder.Property(x => x.UnitPrice).HasColumnName("Unit Price").IsRequired().HasColumnType("money").HasPrecision(19,4);
            builder.Property(x => x.Quantity).HasColumnName("Quantity").IsRequired().HasColumnType("smallint");
            builder.Property(x => x.Discount).HasColumnName("Discount").IsRequired().HasColumnType("real");

            // Foreign keys
            builder.HasRequired(a => a.Order).WithMany(b => b.OrderDetails).HasForeignKey(c => c.OrderId); // Order Details_FK01
            builder.HasRequired(a => a.Product).WithMany(b => b.OrderDetails).HasForeignKey(c => c.ProductId); // Order Details_FK00
        }
    }

    // Products
    public class ProductConfiguration : EntityTypeConfiguration<Product>
    {
 
        public void Config(Microsoft.Data.Entity.Metadata.Builders.EntityTypeBuilder<Product> builder, string schema)
        {
            builder.ToTable("Products", schema);
            builder.HasKey(x => x.ProductId);

            builder.Property(x => x.ProductId).HasColumnName("Product ID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            builder.Property(x => x.SupplierId).HasColumnName("Supplier ID").IsOptional().HasColumnType("int");
            builder.Property(x => x.CategoryId).HasColumnName("Category ID").IsOptional().HasColumnType("int");
            builder.Property(x => x.ProductName).HasColumnName("Product Name").IsRequired().HasColumnType("nvarchar").HasMaxLength(40);
            builder.Property(x => x.EnglishName).HasColumnName("English Name").IsOptional().HasColumnType("nvarchar").HasMaxLength(40);
            builder.Property(x => x.QuantityPerUnit).HasColumnName("Quantity Per Unit").IsOptional().HasColumnType("nvarchar").HasMaxLength(20);
            builder.Property(x => x.UnitPrice).HasColumnName("Unit Price").IsOptional().HasColumnType("money").HasPrecision(19,4);
            builder.Property(x => x.UnitsInStock).HasColumnName("Units In Stock").IsOptional().HasColumnType("smallint");
            builder.Property(x => x.UnitsOnOrder).HasColumnName("Units On Order").IsOptional().HasColumnType("smallint");
            builder.Property(x => x.ReorderLevel).HasColumnName("Reorder Level").IsOptional().HasColumnType("smallint");
            builder.Property(x => x.Discontinued).HasColumnName("Discontinued").IsRequired().HasColumnType("bit");

            // Foreign keys
            builder.HasOptional(a => a.Category).WithMany(b => b.Products).HasForeignKey(c => c.CategoryId); // Products_FK01
            builder.HasOptional(a => a.Supplier).WithMany(b => b.Products).HasForeignKey(c => c.SupplierId); // Products_FK00
        }
    }

    // Shippers
    public class ShipperConfiguration : EntityTypeConfiguration<Shipper>
    {
 
        public void Config(Microsoft.Data.Entity.Metadata.Builders.EntityTypeBuilder<Shipper> builder, string schema)
        {
            builder.ToTable("Shippers", schema);
            builder.HasKey(x => x.ShipperId);

            builder.Property(x => x.ShipperId).HasColumnName("Shipper ID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            builder.Property(x => x.CompanyName).HasColumnName("Company Name").IsRequired().HasColumnType("nvarchar").HasMaxLength(40);
        }
    }

    // Suppliers
    public class SupplierConfiguration : EntityTypeConfiguration<Supplier>
    {
 
        public void Config(Microsoft.Data.Entity.Metadata.Builders.EntityTypeBuilder<Supplier> builder, string schema)
        {
            builder.ToTable("Suppliers", schema);
            builder.HasKey(x => x.SupplierId);

            builder.Property(x => x.SupplierId).HasColumnName("Supplier ID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            builder.Property(x => x.CompanyName).HasColumnName("Company Name").IsRequired().HasColumnType("nvarchar").HasMaxLength(40);
            builder.Property(x => x.ContactName).HasColumnName("Contact Name").IsOptional().HasColumnType("nvarchar").HasMaxLength(30);
            builder.Property(x => x.ContactTitle).HasColumnName("Contact Title").IsOptional().HasColumnType("nvarchar").HasMaxLength(30);
            builder.Property(x => x.Address).HasColumnName("Address").IsOptional().HasColumnType("nvarchar").HasMaxLength(60);
            builder.Property(x => x.City).HasColumnName("City").IsOptional().HasColumnType("nvarchar").HasMaxLength(15);
            builder.Property(x => x.Region).HasColumnName("Region").IsOptional().HasColumnType("nvarchar").HasMaxLength(15);
            builder.Property(x => x.PostalCode).HasColumnName("Postal Code").IsOptional().HasColumnType("nvarchar").HasMaxLength(10);
            builder.Property(x => x.Country).HasColumnName("Country").IsOptional().HasColumnType("nvarchar").HasMaxLength(15);
            builder.Property(x => x.Phone).HasColumnName("Phone").IsOptional().HasColumnType("nvarchar").HasMaxLength(24);
            builder.Property(x => x.Fax).HasColumnName("Fax").IsOptional().HasColumnType("nvarchar").HasMaxLength(24);
        }
    }


    // ************************************************************************
    // Helper Classes

    internal interface EntityTypeConfiguration<TEntity> where TEntity : class
    {
        void Config(Microsoft.Data.Entity.Metadata.Builders.EntityTypeBuilder<TEntity> typeBuilder, string schema);
    }

    internal static class EF7Helper
    {//see https://github.com/aspnet/EntityFramework/wiki/Entity-Framework-Design-Meeting-Notes-June-5,-2014#decision-property-facet-apis
        public static void Add<TEntity>(this ModelBuilder builder, EntityTypeConfiguration<TEntity> cfg, string schema = "dbo")
            where TEntity : class
        {
            builder.Entity<TEntity>(etb => cfg.Config(etb, schema));
        }

        public static PropertyBuilder<TProperty> IsOptional<TProperty>(this PropertyBuilder<TProperty> builder)
        {
            return builder.IsRequired(false);
        }

        public static PropertyBuilder<TProperty> IsUnicode<TProperty>(this PropertyBuilder<TProperty> builder, bool unicode)
        {
            return builder;
        }

        public static PropertyBuilder<TProperty> IsFixedLength<TProperty>(this PropertyBuilder<TProperty> builder)
        {
            return builder;
        }

        public static PropertyBuilder<TProperty> IsMaxLength<TProperty>(this PropertyBuilder<TProperty> builder)
        {
            return builder;
        }

        public static ReferenceNavigationBuilder<TEntity, TRelatedEntity> HasRequired<TEntity, TRelatedEntity>(
            this EntityTypeBuilder<TEntity> builder, Expression<Func<TEntity, TRelatedEntity>> reference = null)
            where TEntity : class
            where TRelatedEntity : class
        {
            return builder.HasOne(reference);
        }

        public static ReferenceNavigationBuilder<TEntity, TRelatedEntity> HasOptional<TEntity, TRelatedEntity>(
            this EntityTypeBuilder<TEntity> builder, Expression<Func<TEntity, TRelatedEntity>> reference = null)
            where TEntity : class
            where TRelatedEntity : class
        {
            return builder.HasOne(reference);
        }

        public static ReferenceReferenceBuilder<TEntity, TRelatedEntity> WithOptional<TEntity, TRelatedEntity>(
            this ReferenceNavigationBuilder<TEntity, TRelatedEntity> builder, Expression<Func<TRelatedEntity, TEntity>> reference = null)
            where TEntity : class
            where TRelatedEntity : class
        {
            return builder.WithOne(reference);
        }

#if false
        public static CollectionNavigationBuilder<TEntity, TRelatedEntity> WithMany<TEntity, TRelatedEntity>(
            this CollectionNavigationBuilder<TEntity, TRelatedEntity> builder, Expression<Func<TRelatedEntity, System.Collections.Generic.IEnumerable<TEntity>>> reference = null)
            where TEntity : class
            where TRelatedEntity : class
        {
            //var innerBuilder = ((Microsoft.Data.Entity.Infrastructure.IInfrastructure<Microsoft.Data.Entity.Metadata.Internal.InternalRelationshipBuilder>)builder).Instance;

            //return innerBuilder.PrincipalEntityType(builder.RelatedEntityType, Microsoft.Data.Entity.Metadata.Internal.ConfigurationSource.Explicit)
            //    .IsUnique(false, Microsoft.Data.Entity.Metadata.Internal.ConfigurationSource.Explicit)
            //    .PrincipalToDependent(collection, Microsoft.Data.Entity.Metadata.Internal.ConfigurationSource.Explicit);
            //TODO: link to another table
            return builder;
        }
#endif

        public static PropertyBuilder<TProperty> HasPrecision<TProperty>(this PropertyBuilder<TProperty> builder, byte precision, byte scale)
        {
            //for decimal/Nullable<decimal>
            //TODO: (precision, scale)
            return builder;
        }

        public static PropertyBuilder<TProperty> HasDatabaseGeneratedOption<TProperty>(
            this PropertyBuilder<TProperty> builder, DatabaseGeneratedOption option)
        {
            switch (option)
            {
                case DatabaseGeneratedOption.None:
                    return builder.ValueGeneratedNever();
                case DatabaseGeneratedOption.Computed:
                    return builder.ValueGeneratedOnAddOrUpdate();
                case DatabaseGeneratedOption.Identity:
                    return builder.ValueGeneratedOnAdd();
                default:
                    throw new ArgumentException("option");
            }
        }
    }
}
// </auto-generated>

